openapi: "3.0.0"
paths:
  /pets:
    post:
      summary: Create a pet
      operationId: createPets
      parameters:
        - name: x-header
          in: header
          description: How many items to return at one time (max 100)
          required: true
          schema:
            type: string
            format: int32
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
  securitySchemes:
    httpBasic:
      type: http
      scheme: basic
security:
  - httpBasic: []
